### ISSUE TITLE
cards.json

### ISSUE THREAD

**Issue by vertex101** [Entrivax/Streamloots-Plugin#2]
how do you setup the cards.json file ?

**Comment by Entrivax** [comment]
Hello, I just pushed a json editor preconfigured to generate that file [here](https://entrivax.github.io/Streamloots-Plugin/json-editor/), I will write some documentation for this plugin later. If you need help for something else, don't hesitate to ask.

To get the card id which is asked for the config, you need to go to your cards list (https://www.streamloots.com/your-username/manage/cards), open the dev tools of your browser (Ctrl+Shift+I or F12), use the element selector (Ctrl+Shift+C):
![Screenshot_20220503_175807](https://user-images.githubusercontent.com/1197915/166490158-c2702f0d-0d54-4170-b1c8-e5153df171ad.png)
Then point the checkbox of the card you want to get the id and click:
![Screenshot_20220503_175856](https://user-images.githubusercontent.com/1197915/166490393-30b1af67-9837-47aa-aa30-f27c2116396f.png)
After that, you should have a span highlighted on the Elements tab of the dev tools:
![Screenshot_20220503_180006](https://user-images.githubusercontent.com/1197915/166490977-56f71f57-8de8-44ff-8278-5f4c09c0d86a.png)
The input of type checkbox right on top of it should have an id, use that id. On my screenshot right here, the id I should get and use is `60f72872acb067003567b01d`.

**Comment by vertex101** [comment]
I see ur able to spawn items but are you able to spawn entities if not what would that take to do ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Entrivax** [comment]
To spawn entities, you should be able to use a chat command like this:
![image](https://user-images.githubusercontent.com/1197915/166588998-c47101cd-abb4-4860-850b-b6e05212222f.png)

**Comment by vertex101** [comment]
Are the commands running as console or as the player? If running as the player then they would need to be oped 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Entrivax** [comment]
The commands are running as console.

**Comment by vertex101** [comment]
One other question is there say away to setup this up on a server that has multiple streamers on it and it only triggers for that streamer when they have a card played 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Entrivax** [comment]
No, since it requires private info from said streamers (their alerts id) that shouldn't be shared, I did not design it to use multiple alerts sources
